import { ClientMlbTeam } from './mlb-team.model';

export const MLB_TEAM_MAP: { [key in ClientMlbTeam]: string } = {
  [ClientMlbTeam.FA]: 'FA',
  [ClientMlbTeam.Bal]: 'Bal',
  [ClientMlbTeam.Bos]: 'Bos',
  [ClientMlbTeam.LAA]: 'LAA',
  [ClientMlbTeam.ChW]: 'ChW',
  [ClientMlbTeam.Cle]: 'Cle',
  [ClientMlbTeam.Det]: 'Det',
  [ClientMlbTeam.KC]: 'KC',
  [ClientMlbTeam.Mil]: 'Mil',
  [ClientMlbTeam.Min]: 'Min',
  [ClientMlbTeam.NYY]: 'NYY',
  [ClientMlbTeam.Oak]: 'Oak',
  [ClientMlbTeam.Sea]: 'Sea',
  [ClientMlbTeam.Tex]: 'Tex',
  [ClientMlbTeam.Tor]: 'Tor',
  [ClientMlbTeam.Atl]: 'Atl',
  [ClientMlbTeam.ChC]: 'ChC',
  [ClientMlbTeam.Cin]: 'Cin',
  [ClientMlbTeam.Hou]: 'Hou',
  [ClientMlbTeam.LAD]: 'LAD',
  [ClientMlbTeam.Wsh]: 'Wsh',
  [ClientMlbTeam.NYM]: 'NYM',
  [ClientMlbTeam.Phi]: 'Phi',
  [ClientMlbTeam.Pit]: 'Pit',
  [ClientMlbTeam.StL]: 'StL',
  [ClientMlbTeam.SD]: 'SD',
  [ClientMlbTeam.SF]: 'SF',
  [ClientMlbTeam.Col]: 'Col',
  [ClientMlbTeam.Mia]: 'Mia',
  [ClientMlbTeam.Ari]: 'Ari',
  [ClientMlbTeam.TB]: 'TB',
} as const;
