export const ROUTE_FRAGMENT = {
  ADMIN: 'admin',
  BASEBALL: 'baseball',
  BATTERS: 'batters',
  DAILY_FANTASY: 'daily-fantasy',
  EMPTY: '',
  FOOTBALL: 'football',
  FORGOT_PASSWORD: 'forgot-password',
  FREE_AGENTS: 'free-agents',
  GAME_ID: ':gameId',
  HOME: 'home',
  LEAGUE: 'league',
  LEAGUE_ID: ':leagueId',
  LEAGUE_PROGRESSION: 'league-progression',
  LOGIN: 'login',
  LOGOUT: 'logout',
  PLAYER: 'player',
  PLAYER_ID: ':playerId',
  PITCHERS: 'pitchers',
  PROFILE: 'profile',
  RESET_PASSWORD: 'reset-password',
  SCOREBOARD: 'scoreboard',
  SIGN_UP: 'sign-up',
  TEAM: 'team',
  TEAM_ID: ':teamId',
  YEAR: ':year',
} as const;
