import { ClientBaseballStatCategory } from './baseball-stat-category.model';
import { ClientBaseballStatType } from './baseball-stat-type.model';
import { BaseballStat } from './mlb-stats.model';

export const MLB_STATS_MAP = {
  [BaseballStat.AB]: {
    abbrev: 'AB',
    description: 'At Bats',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.H]: {
    abbrev: 'H',
    description: 'Hits',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.AVG]: {
    abbrev: 'AVG',
    description: 'Batting Average',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.DOUBLE]: {
    abbrev: '2B',
    description: 'Doubles',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.TRIPLE]: {
    abbrev: '3B',
    description: 'Triples',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.HR]: {
    abbrev: 'HR',
    description: 'Home Runs',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.XBH]: {
    abbrev: 'XBH',
    description: 'Extra Base Hits',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.SINGLE]: {
    abbrev: '1B',
    description: 'Singles',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.TB]: {
    abbrev: 'TB',
    description: 'Total Bases',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.SLG]: {
    abbrev: 'SLG',
    description: 'Slugging Pct',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.BB]: {
    abbrev: 'BB',
    description: 'Walks',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.IBB]: {
    abbrev: 'IBB',
    description: 'Intentional Walks',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.HBP]: {
    abbrev: 'HBP',
    description: 'Hit by Pitch',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.SF]: {
    abbrev: 'SF',
    description: 'Sacrifice Flies',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.SH]: {
    abbrev: 'SH',
    description: 'Sacrifice Hits',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.SAC]: {
    abbrev: 'SAC',
    description: 'Sacrifices',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.PA]: {
    abbrev: 'PA',
    description: 'Plate Appearances',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.OBP]: {
    abbrev: 'OBP',
    description: 'On Base Pct',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.OPS]: {
    abbrev: 'OPS',
    description: 'On Base plus Slugging Pct',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.RC]: {
    abbrev: 'RC',
    description: 'Runs Created',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.R]: {
    abbrev: 'R',
    description: 'Runs Scored',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.RBI]: {
    abbrev: 'RBI',
    description: 'Runs Batted In',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.GWRBI]: {
    abbrev: 'GWRBI',
    description: 'Game Winning RBI',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.SB]: {
    abbrev: 'SB',
    description: 'Stolen Bases',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.CS]: {
    abbrev: 'CS',
    description: 'Caught Stealing',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.SBN]: {
    abbrev: 'SBN',
    description: 'Net Stolen Bases',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.GIDP]: {
    abbrev: 'GIDP',
    description: 'Ground into Double Plays',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.KO]: {
    abbrev: 'KO',
    description: 'Strikeouts',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.TP]: {
    abbrev: 'TP',
    description: 'Total Pitches',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.PPA]: {
    abbrev: 'PPA',
    description: 'Pitches per Plate Appearance',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.CYC]: {
    abbrev: 'CYC',
    description: 'Hitting for the Cycle',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.GSHR]: {
    abbrev: 'GSHR',
    description: 'Grand Slam Home Runs',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.APP]: {
    abbrev: 'APP',
    description: 'Appearances',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.GS]: {
    abbrev: 'GS',
    description: 'Games Started',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.IP]: {
    abbrev: 'IP',
    description: 'Innings Pitched',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.BF]: {
    abbrev: 'BF',
    description: 'Batters Faced',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.PC]: {
    abbrev: 'PC',
    description: 'Pitch Count',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.HA]: {
    abbrev: 'HA',
    description: 'Hits Allowed',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.BAA]: {
    abbrev: 'BAA',
    description: 'Batting Average Against',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.BBI]: {
    abbrev: 'BBI',
    description: 'Walks Issued',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.IBBI]: {
    abbrev: 'IBBI',
    description: 'Intentional Walks',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.WHIP]: {
    abbrev: 'WHIP',
    description: 'Walks plus Hits Per Innings Pitched',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.HB]: {
    abbrev: 'HB',
    description: 'Hit Batsmen',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.OBA]: {
    abbrev: 'OBA',
    description: 'On Base Pct Against',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.RA]: {
    abbrev: 'RA',
    description: 'Runs Allowed',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.ER]: {
    abbrev: 'ER',
    description: 'Earned Runs',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.HRA]: {
    abbrev: 'HRA',
    description: 'Home Runs Allowed',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.ERA]: {
    abbrev: 'ERA',
    description: 'Earned Run Average',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.K]: {
    abbrev: 'K',
    description: 'Strikeouts',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.K_9]: {
    abbrev: 'K/9',
    description: 'Strikeouts per 9 Innings',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.WP]: {
    abbrev: 'WP',
    description: 'Wild Pitches',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.B]: {
    abbrev: 'B',
    description: 'Balks',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.PKO]: {
    abbrev: 'PKO',
    description: 'Pick Offs',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.W]: {
    abbrev: 'W',
    description: 'Wins',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.L]: {
    abbrev: 'L',
    description: 'Losses',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.WIN_PCT]: {
    abbrev: 'WIN%',
    description: 'Win Pct',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.SOP]: {
    abbrev: 'SOP',
    description: 'Save Opportunities',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.SV]: {
    abbrev: 'SV',
    description: 'Saves',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.BS]: {
    abbrev: 'BS',
    description: 'Blown Saves',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.SV_PCT]: {
    abbrev: 'SV%',
    description: 'Save Pct',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.HD]: {
    abbrev: 'HD',
    description: 'Holds',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.IRS]: {
    abbrev: 'IRS',
    description: 'Inherited Runners Scored',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.CG]: {
    abbrev: 'CG',
    description: 'Complete Games',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.QS]: {
    abbrev: 'QS',
    description: 'Quality Starts',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.SO]: {
    abbrev: 'SO',
    description: 'Shutouts',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.NH]: {
    abbrev: 'NH',
    description: 'No Hitters',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.PG]: {
    abbrev: 'PG',
    description: 'Perfect Games',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.FC]: {
    abbrev: 'FC',
    description: 'Fielding Chances',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Defense,
  },
  [BaseballStat.PO]: {
    abbrev: 'PO',
    description: 'Put Outs',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Defense,
  },
  [BaseballStat.AST]: {
    abbrev: 'AST',
    description: 'Assists',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Defense,
  },
  [BaseballStat.OFAST]: {
    abbrev: 'OFAST',
    description: 'Outfield Assists',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Defense,
  },
  [BaseballStat.FPCT]: {
    abbrev: 'FPCT',
    description: 'Fielding Pct',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Defense,
  },
  [BaseballStat.E]: {
    abbrev: 'E',
    description: 'Errors',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Defense,
  },
  [BaseballStat.DPT]: {
    abbrev: 'DPT',
    description: 'Double Plays Turned',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Defense,
  },
  [BaseballStat.BTW]: {
    abbrev: 'BTW',
    description: 'Batter Team Win',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.BTL]: {
    abbrev: 'BTL',
    description: 'Batter Team Loss',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.PTW]: {
    abbrev: 'PTW',
    description: 'Pitcher Team Win',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.PTL]: {
    abbrev: 'PTL',
    description: 'Pitcher Team Loss',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.SFA]: {
    abbrev: 'SFA',
    description: 'Sacrifice Flies Allowed',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.SHA]: {
    abbrev: 'SHA',
    description: 'Sacrifice Hits Allowed',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.CIA]: {
    abbrev: 'CIA',
    description: 'Catcher Interference Allowed',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.GP]: {
    abbrev: 'GP',
    description: 'Games Played',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.K_BB]: {
    abbrev: 'K/BB',
    description: 'Strikeout to Walk Ratio',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.SVHD]: {
    abbrev: 'SVHD',
    description: 'Saves Plus Holds',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.PBS]: {
    abbrev: 'PBS',
    description: 'Probable Start',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.fip]: {
    abbrev: 'FIP',
    description: 'Fielding Independent Pitching (FIP)',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.wOBA]: {
    abbrev: 'wOBA',
    description: 'Weighted On-Base Average (wOBA)',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.wRAA]: {
    abbrev: 'wRAA',
    description: 'Weighted Runs Above Average (wRAA)',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.BABIP]: {
    abbrev: 'BABIP',
    description: 'Batting Average on Balls In Play (BABIP)',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.ISO]: {
    abbrev: 'ISO',
    description: 'Isolated Power',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
  [BaseballStat.LOB_PCT]: {
    abbrev: 'LOB%',
    description: 'Left On Base %',
    statCategoryId: ClientBaseballStatCategory.Pitching,
    statTypeId: ClientBaseballStatType.Pitching,
  },
  [BaseballStat.wRC]: {
    abbrev: 'wRC',
    description: 'Weighted Runs Created',
    statCategoryId: ClientBaseballStatCategory.Batting,
    statTypeId: ClientBaseballStatType.Batting,
  },
} as const;

export const MLB_STATS_LIST = Object.entries(MLB_STATS_MAP).map(([key, stat]) => {
  return {
    ...stat,
    id: key,
  };
});
export const MLB_STATS_KEYS = Object.keys(MLB_STATS_MAP);

export const BATTER_STATS_LIST = MLB_STATS_LIST.filter(s => s.statTypeId === ClientBaseballStatType.Batting);
export const BATTER_STATS_CATEGORY_LIST = MLB_STATS_LIST.filter(s => s.statCategoryId === ClientBaseballStatCategory.Batting);
export const BATTER_STATS_LIST_OPTIONS = BATTER_STATS_LIST.map(p => ({ label: p.description, value: p.id }));

export const PITCHER_STATS_LIST = MLB_STATS_LIST.filter(s => s.statTypeId === ClientBaseballStatType.Pitching);
export const PITCHER_STATS_CATEGORY_LIST = MLB_STATS_LIST.filter(s => s.statCategoryId === ClientBaseballStatCategory.Pitching);

export const DEFENSE_STATS_LIST = MLB_STATS_LIST.filter(s => s.statTypeId === ClientBaseballStatType.Defense);
