import { LineupEntityMap } from '@sdk/espn-client-models/lineup.model';
import { ClientMlbPosition } from '../position/mlb-position.model';
import { ClientBaseballLineupSlot } from './lineup.model';

/**
 * Main baseball lineup slot map
 */
export const BASEBALL_LINEUP_MAP: LineupEntityMap = {
  [ClientBaseballLineupSlot.None]: {
    abbrev: null,
    active: false,
    bench: false,
    displayOrder: 0,
    eligiblePositions: [],
    id: ClientBaseballLineupSlot.None,
    lineupSlotEligible: true,
    name: null,
    parentId: ClientBaseballLineupSlot.None,
    starter: false,
  },
  [ClientBaseballLineupSlot.C]: {
    abbrev: 'C',
    active: true,
    bench: false,
    displayOrder: 0,
    eligiblePositions: [ClientMlbPosition.Catcher],
    id: ClientBaseballLineupSlot.C,
    lineupSlotEligible: true,
    name: 'Catcher',
    parentId: 12,
    starter: true,
  },
  [ClientBaseballLineupSlot.FirstBase]: {
    abbrev: '1B',
    active: true,
    bench: false,
    displayOrder: 1,
    eligiblePositions: [ClientMlbPosition.FirstBase],
    id: ClientBaseballLineupSlot.FirstBase,
    lineupSlotEligible: true,
    name: 'First Base',
    parentId: 7,
    starter: true,
  },
  [ClientBaseballLineupSlot.SecondBase]: {
    abbrev: '2B',
    active: true,
    bench: false,
    displayOrder: 2,
    eligiblePositions: [ClientMlbPosition.SecondBase],
    id: ClientBaseballLineupSlot.SecondBase,
    lineupSlotEligible: true,
    name: 'Second Base',
    parentId: 6,
    starter: true,
  },
  [ClientBaseballLineupSlot.ThirdBase]: {
    abbrev: '3B',
    active: true,
    bench: false,
    displayOrder: 3,
    eligiblePositions: [ClientMlbPosition.ThirdBase],
    id: ClientBaseballLineupSlot.ThirdBase,
    lineupSlotEligible: true,
    name: 'Third Base',
    parentId: 7,
    starter: true,
  },
  [ClientBaseballLineupSlot.SS]: {
    abbrev: 'SS',
    active: true,
    bench: false,
    displayOrder: 4,
    eligiblePositions: [ClientMlbPosition.Shortstop],
    id: ClientBaseballLineupSlot.SS,
    lineupSlotEligible: true,
    name: 'Shortstop',
    parentId: 6,
    starter: true,
  },
  [ClientBaseballLineupSlot.OF]: {
    abbrev: 'OF',
    active: true,
    bench: false,
    displayOrder: 11,
    eligiblePositions: [ClientMlbPosition.LeftField, ClientMlbPosition.CenterField, ClientMlbPosition.RightField],
    id: ClientBaseballLineupSlot.OF,
    lineupSlotEligible: true,
    name: 'Outfield',
    parentId: 12,
    starter: true,
  },
  [ClientBaseballLineupSlot.SecondOrSS]: {
    abbrev: '2B/SS',
    active: true,
    bench: false,
    displayOrder: 5,
    eligiblePositions: [ClientMlbPosition.SecondBase, ClientMlbPosition.Shortstop],
    id: ClientBaseballLineupSlot.SecondOrSS,
    lineupSlotEligible: true,
    name: 'Middle Infielder',
    parentId: 12,
    starter: true,
  },
  [ClientBaseballLineupSlot.FirstOrThird]: {
    abbrev: '1B/3B',
    active: true,
    bench: false,
    displayOrder: 6,
    eligiblePositions: [ClientMlbPosition.FirstBase, ClientMlbPosition.ThirdBase],
    id: ClientBaseballLineupSlot.FirstOrThird,
    lineupSlotEligible: true,
    name: 'Corner Infielder',
    parentId: 12,
    starter: true,
  },
  [ClientBaseballLineupSlot.LF]: {
    abbrev: 'LF',
    active: true,
    bench: false,
    displayOrder: 8,
    eligiblePositions: [ClientMlbPosition.LeftField],
    id: ClientBaseballLineupSlot.LF,
    lineupSlotEligible: true,
    name: 'Left Field',
    parentId: 5,
    starter: true,
  },
  [ClientBaseballLineupSlot.CF]: {
    abbrev: 'CF',
    active: true,
    bench: false,
    displayOrder: 9,
    eligiblePositions: [ClientMlbPosition.CenterField],
    id: ClientBaseballLineupSlot.CF,
    lineupSlotEligible: true,
    name: 'Center Field',
    parentId: 5,
    starter: true,
  },
  [ClientBaseballLineupSlot.RF]: {
    abbrev: 'RF',
    active: true,
    bench: false,
    displayOrder: 10,
    eligiblePositions: [ClientMlbPosition.RightField],
    id: ClientBaseballLineupSlot.RF,
    lineupSlotEligible: true,
    name: 'Right Field',
    parentId: 5,
    starter: true,
  },
  [ClientBaseballLineupSlot.DH]: {
    abbrev: 'DH',
    active: true,
    bench: false,
    displayOrder: 12,
    eligiblePositions: [ClientMlbPosition.DesignatedHitter],
    id: ClientBaseballLineupSlot.DH,
    lineupSlotEligible: true,
    name: 'Designated Hitter',
    parentId: 12,
    starter: true,
  },
  [ClientBaseballLineupSlot.UTIL]: {
    abbrev: 'UTIL',
    active: true,
    bench: false,
    displayOrder: 13,
    eligiblePositions: [
      ClientMlbPosition.Catcher,
      ClientMlbPosition.FirstBase,
      ClientMlbPosition.SecondBase,
      ClientMlbPosition.ThirdBase,
      ClientMlbPosition.Shortstop,
      ClientMlbPosition.LeftField,
      ClientMlbPosition.CenterField,
      ClientMlbPosition.RightField,
      ClientMlbPosition.DesignatedHitter,
    ],
    id: ClientBaseballLineupSlot.UTIL,
    lineupSlotEligible: true,
    name: 'Utility',
    parentId: 21,
    starter: true,
  },
  [ClientBaseballLineupSlot.P]: {
    abbrev: 'P',
    active: true,
    bench: false,
    displayOrder: 14,
    eligiblePositions: [ClientMlbPosition.StartingPitcher, ClientMlbPosition.ReliefPitcher],
    id: ClientBaseballLineupSlot.P,
    lineupSlotEligible: true,
    name: 'Pitcher',
    parentId: 22,
    starter: true,
  },
  [ClientBaseballLineupSlot.SP]: {
    abbrev: 'SP',
    active: true,
    bench: false,
    displayOrder: 15,
    eligiblePositions: [ClientMlbPosition.StartingPitcher],
    id: ClientBaseballLineupSlot.SP,
    lineupSlotEligible: true,
    name: 'Starting Pitcher',
    parentId: 13,
    starter: true,
  },
  [ClientBaseballLineupSlot.RP]: {
    abbrev: 'RP',
    active: true,
    bench: false,
    displayOrder: 16,
    eligiblePositions: [ClientMlbPosition.ReliefPitcher],
    id: 15,
    lineupSlotEligible: true,
    name: 'Relief Pitcher',
    parentId: 13,
    starter: true,
  },
  [ClientBaseballLineupSlot.BE]: {
    abbrev: 'BE',
    active: false,
    bench: true,
    displayOrder: 17,
    eligiblePositions: [
      ClientMlbPosition.StartingPitcher,
      ClientMlbPosition.Catcher,
      ClientMlbPosition.FirstBase,
      ClientMlbPosition.SecondBase,
      ClientMlbPosition.ThirdBase,
      ClientMlbPosition.Shortstop,
      ClientMlbPosition.LeftField,
      ClientMlbPosition.CenterField,
      ClientMlbPosition.RightField,
      ClientMlbPosition.DesignatedHitter,
      ClientMlbPosition.ReliefPitcher,
    ],
    id: ClientBaseballLineupSlot.BE,
    lineupSlotEligible: true,
    name: 'Bench',
    parentId: 23,
    starter: false,
  },
  [ClientBaseballLineupSlot.IL]: {
    abbrev: 'IL',
    active: false,
    bench: false,
    displayOrder: 18,
    eligiblePositions: [
      ClientMlbPosition.StartingPitcher,
      ClientMlbPosition.Catcher,
      ClientMlbPosition.FirstBase,
      ClientMlbPosition.SecondBase,
      ClientMlbPosition.ThirdBase,
      ClientMlbPosition.Shortstop,
      ClientMlbPosition.LeftField,
      ClientMlbPosition.CenterField,
      ClientMlbPosition.RightField,
      ClientMlbPosition.DesignatedHitter,
      ClientMlbPosition.ReliefPitcher,
    ],
    id: ClientBaseballLineupSlot.IL,
    lineupSlotEligible: true,
    name: 'Injured List',
    parentId: 23,
    starter: false,
  },
  [ClientBaseballLineupSlot.INV]: {
    abbrev: 'INV',
    active: false,
    bench: false,
    displayOrder: 19,
    eligiblePositions: [],
    id: ClientBaseballLineupSlot.INV,
    lineupSlotEligible: false,
    name: 'Invalid Player',
    parentId: 23,
    starter: false,
  },
  [ClientBaseballLineupSlot.IF]: {
    abbrev: 'IF',
    active: true,
    bench: false,
    displayOrder: 7,
    eligiblePositions: [
      ClientMlbPosition.FirstBase,
      ClientMlbPosition.SecondBase,
      ClientMlbPosition.ThirdBase,
      ClientMlbPosition.Shortstop,
    ],
    id: ClientBaseballLineupSlot.IF,
    lineupSlotEligible: true,
    name: 'Infielder',
    parentId: 12,
    starter: true,
  },
  [ClientBaseballLineupSlot.B]: {
    abbrev: 'B',
    active: true,
    bench: false,
    displayOrder: 0,
    eligiblePositions: [
      ClientMlbPosition.Catcher,
      ClientMlbPosition.FirstBase,
      ClientMlbPosition.SecondBase,
      ClientMlbPosition.ThirdBase,
      ClientMlbPosition.Shortstop,
      ClientMlbPosition.LeftField,
      ClientMlbPosition.CenterField,
      ClientMlbPosition.RightField,
      ClientMlbPosition.DesignatedHitter,
    ],
    id: ClientBaseballLineupSlot.B,
    lineupSlotEligible: false,
    name: 'Batters',
    parentId: 21,
    starter: false,
  },
  [ClientBaseballLineupSlot.P2]: {
    abbrev: 'P2',
    active: true,
    bench: false,
    displayOrder: 0,
    eligiblePositions: [ClientMlbPosition.StartingPitcher, ClientMlbPosition.ReliefPitcher],
    id: ClientBaseballLineupSlot.P2,
    lineupSlotEligible: false,
    name: 'Pitchers',
    parentId: 22,
    starter: false,
  },
  [ClientBaseballLineupSlot.MISC]: {
    abbrev: 'MISC',
    active: true,
    bench: false,
    displayOrder: 0,
    id: ClientBaseballLineupSlot.MISC,
    lineupSlotEligible: false,
    name: 'Miscellaneous',
    parentId: 23,
    starter: false,
    eligiblePositions: [],
  },
};

/**
 * Batting lineup slots
 */
export const BATTING_LINEUP_SLOTS = [
  ClientBaseballLineupSlot.C,
  ClientBaseballLineupSlot.FirstBase,
  ClientBaseballLineupSlot.SecondBase,
  ClientBaseballLineupSlot.ThirdBase,
  ClientBaseballLineupSlot.SS,
  ClientBaseballLineupSlot.OF,
  ClientBaseballLineupSlot.SecondOrSS,
  ClientBaseballLineupSlot.FirstOrThird,
  ClientBaseballLineupSlot.LF,
  ClientBaseballLineupSlot.CF,
  ClientBaseballLineupSlot.RF,
  ClientBaseballLineupSlot.DH,
  ClientBaseballLineupSlot.UTIL,
] as const;

/**
 * Simplified display for common lineup slots.
 *
 * Excludes multi position lineup slots: LF, RF, 2B/SS, 2B/3B, etc.
 */
export const LINEUP_DISPLAY_LIST = [
  ClientBaseballLineupSlot.FirstBase,
  ClientBaseballLineupSlot.SecondBase,
  ClientBaseballLineupSlot.SS,
  ClientBaseballLineupSlot.ThirdBase,
  ClientBaseballLineupSlot.C,
  ClientBaseballLineupSlot.OF,
  ClientBaseballLineupSlot.DH,
  ClientBaseballLineupSlot.SP,
  ClientBaseballLineupSlot.RP,
] as const;

export const LINEUP_DISPLAY_SET = new Set(LINEUP_DISPLAY_LIST);

/**
 * Pitching lineup slots
 */
export const PITCHING_LINEUP_SLOTS = [ClientBaseballLineupSlot.P, ClientBaseballLineupSlot.SP, ClientBaseballLineupSlot.RP] as const;
export const PITCHING_LINEUP_IDS: Set<ClientBaseballLineupSlot> = new Set([
  ClientBaseballLineupSlot.P,
  ClientBaseballLineupSlot.SP,
  ClientBaseballLineupSlot.RP,
  ClientBaseballLineupSlot.P2,
]);

export const BASEBALL_LINEUP_LIST = Object.values(BASEBALL_LINEUP_MAP);
export const BASEBALL_LINEUP_STARTERS = BASEBALL_LINEUP_LIST.filter(p => p.starter);
export const BASEBALL_LINEUP_BENCH = BASEBALL_LINEUP_LIST.filter(p => p.bench);
